sonar.projectKey=taller-sast-monorepo
sonar.projectName=Taller SAST Monorepo
sonar.sources=apps
sonar.sourceEncoding=UTF-8

# Excluir archivos que no quieres que afecten tu Quality Gate
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**, adarboleda/**, **/*.spec.js, **/*.test.js, **/*.spec.ts, **/*.test.ts
